apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  labels:
    app: carcare
data:
  Caddyfile: |-
    carcare.trade:443 {
      root * /srv/app/public
      tls /etc/ssl/carcare.trade.crt /etc/ssl/carcare.trade.key
      php_fastcgi unix//var/run/php/php-fpm.sock
    }
