apiVersion: apps/v1
kind: Deployment
metadata:
  name: carcare-deploy
  labels:
    app: carcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carcare
  template:
    metadata:
      labels:
        app: carcare
    spec: 
      containers:
      - name: caddy
        image: caddy:2
        imagePullPolicy: Always
        command: ["caddy", "--conf", "/Caddyfile"]
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        volumeMounts:
        - mountPath: /Caddyfile
          name: caddy-config
          subPath: Caddyfile
      - name: php-fpm
        image: asktestacr.azurecr.io/php-fpm-8-kusala:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
            items:
              - key: Caddyfile
                path: Caddyfile
                mode: 0644