apiVersion: apps/v1
kind: Deployment
metadata:
  name: carcare-deploy
  labels:
    app: carcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carcare
  template:
    metadata:
      labels:
        app: carcare
    spec: 
      containers:
        - name: caddy
          image: asktestacr.azurecr.io/kusala_caddy:v1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: http3
              containerPort: 443
              protocol: UDP
          volumeMounts:
            - name: config 
              mountPath: /etc/caddy
              readOnly: true
            - name: php-socket 
              mountPath: /var/run/php

        - name: php-fpm
          image: asktestacr.azurecr.io/carcare_php:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: php-socket
              mountPath: /var/run/php

        - name: db
          image: postgres:13-alpine
          imagePullPolicy: Always
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust

      volumes:
        - name: config
          configMap:
            name: caddy-config
        - name: db-data
          emptyDir: {}
        - name: php-socket
          emptyDir: {}